### ISSUE TITLE
Problem with Curl after Null-safety Migration

### ISSUE THREAD

**Issue by andresruizdev** [isoos/http_client#13]
After migrating to null-safety, Curl is no longer working due to an error that occurs when casting an old List<String> type to List<String?>. This error is encountered while trying to use the Process.run() method to send a request.

```dart
var prf = Process.run(executable ?? 'curl', args as List<String>,
        stdoutEncoding: null);
```

**Comment by isoos** [comment]
Interested in a fix? I'll accept and review PRs.

**Comment by andresruizdev** [comment]
Yes, I'm. I'am working on some features for curl. Thanks

**Comment by andresruizdev** [comment]
Hello, @isoos I made a pull request to fix this issue and add some features to the CurlClient class
