### ISSUE TITLE
socks4 and socks4a curl support

### ISSUE THREAD

**Issue by utopicnarwhal** [isoos/http_client#5]
Can you add other socks types support for curl?

**Comment by isoos** [comment]
I'm happy to take PRs :)

**Comment by utopicnarwhal** [comment]
this is my first PR.
done: https://github.com/isoos/http_client/pull/6

**Comment by jntagadiad** [comment]
when using socks5, how to setup the auth of proxy?

**Comment by isoos** [comment]
How do you set it up for command line `curl`?

**Comment by jntagadiad** [comment]
@isoos I dont know how. is it possible to use socks5 with auth with your work sir?

**Comment by isoos** [comment]
@0wzZZzz6 I'm no `curl` expert, sorry. If you figure it out with `curl`, it will be possible to support it via command-line arguments. The harder path would be to support it natively by implementing socks protocols, but I have even less experience with that.

**Comment by jntagadiad** [comment]
when using `username:password@server_ip:port` I got an error saying permission denied even if its correct.

**Comment by jntagadiad** [comment]
I keep on testing it on a emulator. but now I tested it on real device. It works! thanks
