### ISSUE TITLE
curl socks5 post request.

### ISSUE THREAD

**Issue by jntagadiad** [isoos/http_client#8]
When I tried to put a body in my request I get this error.

`[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Exception: Sending body is not yet supported.`

**Comment by andresruizdev** [comment]
Same error here... Searching a bit through the code, I found that plugin does not support any request with body using curl.
![image](https://user-images.githubusercontent.com/29277715/103708828-5034a380-4f7f-11eb-9e34-095e1121d271.png)

**Comment by isoos** [comment]
The long term solution should be adopting a socks5 library like [this](https://pub.dev/packages/socks5), instead of calling `curl`. Anybody interested in contributing to it?

**Comment by andresruizdev** [comment]
My first Pull Request is to partially add body and Post support to CURL client, this will close this issue.
Please check: #9
